import { CheckCircle2, Clock3, Database, ExternalLink, Radar, ShieldCheck, TriangleAlert } from 'lucide-react'
import sources from '../data/sources.json'
import { useJobs } from '../context/JobContext'
const stamp = value => value ? new Date(value).toLocaleString() : 'Not run yet'
export default function Automation() {
  const { scanStatus: scan } = useJobs()
  const cards = [
    ['Automation status', scan.automationStatus || scan.status, Radar], ['Last successful scan', stamp(scan.lastSuccessfulScan), Clock3], ['Last failed scan', stamp(scan.lastFailedScan), Clock3], ['Next scan', stamp(scan.nextScan), Clock3],
    ['Jobs fetched', scan.jobsFetched, Database], ['Invalid rejected', scan.invalidRejected, ShieldCheck], ['Unrelated rejected', scan.unrelatedRejected, ShieldCheck],
    ['Senior rejected', scan.seniorRejected, ShieldCheck], ['3+ years rejected', scan.experienceRejected, ShieldCheck], ['Duplicates removed', scan.duplicatesRemoved, ShieldCheck],
    ['Jobs indexed', scan.jobsIndexed, CheckCircle2], ['80%+ jobs', scan.highMatchJobs, CheckCircle2], ['90%+ jobs', scan.excellentMatchJobs, CheckCircle2]
  ]
  return <><div className="manual-banner"><ShieldCheck/><div><strong>Job applications are not automatically submitted.</strong><p>Final application submission requires manual review.</p></div></div><div className="automation-grid">{cards.map(([label, value, Icon]) => <article className="stat-card" key={label}><Icon/><div><span>{label}</span><strong>{value ?? 0}</strong></div></article>)}</div><section className="panel"><div className="section-head"><div><p className="eyebrow">LATEST SOURCE RESULTS</p><h3>Real permitted APIs</h3></div><span className="status status-saved">Every 6 hours</span></div><div className="source-list">{sources.map(source => { const result = scan.sourceStats?.find(item => item.name === source.name); return <article key={source.name}><div className={`source-icon ${source.enabled ? 'active' : ''}`}><Database/></div><div><strong>{source.name}</strong><small>Status {result?.status || 'Not run'} · HTTP {result?.httpStatus?.join(', ') || 'not run'} · {result?.rawJobs ?? 0} fetched · {source.requiresSecret ? 'Secret required' : 'No key required'}</small></div><a href={source.documentation} target="_blank" rel="noreferrer">{source.enabled ? 'Enabled' : 'Disabled'} <ExternalLink size={13}/></a></article> })}</div><div className="architecture"><code>Fetch</code><b>→</b><code>Validate</code><b>→</b><code>Normalize</code><b>→</b><code>Deduplicate</code><b>→</b><code>CV score</code><b>→</b><code>Rank</code></div>{scan.errors?.length > 0 && <div className="security-box"><TriangleAlert/><strong>Scan errors</strong>{scan.errors.map(error => <p key={error}>{error}</p>)}</div>}<a className="button button-primary" href="https://github.com/kisip/kisip-jobpilot/actions/workflows/discover-jobs.yml" target="_blank" rel="noreferrer">Run Safe job discovery <ExternalLink size={15}/></a><p className="fine-print">Open the link, choose “Run workflow,” select main, and confirm. The public frontend never stores a GitHub token.</p></section></>
}
