import { useMemo } from 'react'
import preferences from '../config/jobPreferences'
import { ArrowRight, BriefcaseBusiness, CalendarDays, Radio, Sparkles, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import JobTable from '../components/JobTable'
import { useJobs } from '../context/JobContext'

export default function Dashboard() {
  const { jobs } = useJobs(); const today = new Date(); const cutoff = new Date(today); cutoff.setDate(today.getDate()-7)
  const counts = useMemo(() => Object.fromEntries(['New','Saved','Applied','Interview','Rejected','Offer'].map(s=>[s,jobs.filter(j=>j.status===s).length])),[jobs])
  const stats = [{label:'Total Jobs Found',value:jobs.length,icon:BriefcaseBusiness},{label:'New Jobs',value:counts.New,icon:Sparkles},{label:'Saved Jobs',value:counts.Saved,icon:Star},{label:'Applied',value:counts.Applied,icon:ArrowRight},{label:'Interviews',value:counts.Interview,icon:CalendarDays},{label:'Rejected',value:counts.Rejected,icon:Radio},{label:'Offers',value:counts.Offer,icon:Sparkles}]
  const insights = [{label:'Found today',value:jobs.filter(j=>j.dateFound===today.toISOString().slice(0,10)).length},{label:'Found this week',value:jobs.filter(j=>new Date(j.dateFound)>=cutoff).length},{label:'High match jobs',value:jobs.filter(j=>j.matchScore>=preferences.highMatchThreshold).length},{label:'Remote jobs',value:jobs.filter(j=>j.workMode==='Remote').length}]
  const chart = ['New','Saved','Applied','Interview','Offer'].map(name=>({name,value:counts[name]}))
  return <><div className="welcome"><div><p className="eyebrow">GOOD MORNING, JOB SEEKER</p><h2>Your next opportunity is<br/><span>closer than you think.</span></h2><p>Track, prioritize, and apply with confidence. You stay in control.</p></div><div className="profile-card"><p className="eyebrow">TARGET PROFILE</p><strong>{preferences.candidateProfile.title}</strong><dl><div><dt>Experience</dt><dd>{preferences.candidateProfile.professionalExperience}</dd></div><div><dt>Preferred range</dt><dd>{preferences.candidateProfile.preferredExperienceRange}</dd></div><div><dt>Locations</dt><dd>{preferences.locations.join(', ')}</dd></div></dl><span className="scan-pill"><i/>Discovery active <small>Manual application only</small></span></div></div><div className="stat-grid">{stats.map(({label,value,icon:Icon})=><article className="stat-card" key={label}><div><span>{label}</span><strong>{value}</strong></div><Icon/></article>)}</div><div className="insight-grid">{insights.map(i=><article key={i.label}><span>{i.label}</span><strong>{i.value}</strong></article>)}</div><div className="dashboard-grid"><section className="panel chart-panel"><div className="section-head"><div><p className="eyebrow">PIPELINE</p><h3>Application progress</h3></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#1b2c40" vertical={false}/><XAxis dataKey="name" stroke="#718096"/><YAxis allowDecimals={false} stroke="#718096"/><Tooltip contentStyle={{background:'#0d1c2e',border:'1px solid #24364d'}}/><Bar dataKey="value" fill="#20d5b3" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></section><section className="panel focus-panel"><p className="eyebrow">WEEKLY FOCUS</p><h3>Keep momentum</h3><div className="ring"><strong>{counts.Applied}</strong><span>applications</span></div><p>Review high-match jobs before their listings close.</p><Link className="button button-primary" to="/jobs">Browse jobs <ArrowRight size={16}/></Link></section></div><section className="panel"><div className="section-head"><div><p className="eyebrow">TOP MATCHES</p><h3>Worth your attention</h3></div><Link to="/jobs">View all <ArrowRight size={15}/></Link></div><JobTable jobs={[...jobs].sort((a,b)=>b.matchScore-a.matchScore).slice(0,4)} onEdit={()=>{}}/></section></>
}
