import { useMemo } from 'react'
import preferences from '../config/jobPreferences'
import { ArrowRight, BriefcaseBusiness, CalendarDays, Radio, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useJobs } from '../context/JobContext'
import { dashboardCounters, sortJobs } from '../services/jobService'
import { freshnessCounts } from '../services/jobFilterService'

const jobTime = job => new Date(job.postedAt || job.discoveredAt || 0).getTime()
const MiniList = ({ jobs, empty='Nothing here yet.' }) => <div className="mini-job-list">{jobs.length ? jobs.map(job=><article key={job.id}><div><strong>{job.title}</strong><small>{job.company} · {job.source}</small></div><span>{job.matchScore}%</span></article>) : <p className="fine-print">{empty}</p>}</div>
export default function Dashboard(){
  const { jobs, settings, scanStatus }=useJobs()
  const counts=useMemo(()=>dashboardCounters(jobs),[jobs]), fresh=useMemo(()=>freshnessCounts(jobs),[jobs]), now=Date.now(), weekAgo=now-7*86400000
  const applications=jobs.filter(job=>job.applicationStartedAt||job.applicationDate), today=new Date().toISOString().slice(0,10)
  const appliedToday=applications.filter(job=>String(job.applicationDate||'').slice(0,10)===today).length
  const queue=sortJobs(jobs.filter(job=>job.matchScore>=80&&!['Applied','Screening','Interview','Technical Interview','HR Interview','Rejected','Offer','Withdrawn'].includes(job.status)&&jobTime(job)>=weekAgo))
  const followups=applications.filter(job=>job.followUpDate&&new Date(job.followUpDate).getTime()<=now).sort((a,b)=>new Date(a.followUpDate)-new Date(b.followUpDate))
  const stats=[['Total indexed jobs',counts.total,BriefcaseBusiness],['New in 24 hours',fresh.day,Sparkles],['New in 7 days',fresh.week,CalendarDays],['Applied',counts.applied,ArrowRight],['Interviews',counts.interviews,CalendarDays],['Rejected',counts.rejected,Radio],['Offers',counts.offers,Sparkles],['High-match jobs',counts.good,Sparkles],['Remote jobs',counts.remote,BriefcaseBusiness],['Started, unconfirmed',jobs.filter(j=>j.status==='Application Started').length,ArrowRight]]
  return <><div className="welcome"><div><p className="eyebrow">CV-DRIVEN JOB DISCOVERY</p><h2>Your next opportunity is<br/><span>ranked automatically.</span></h2><p>Review high matches, apply on the official site, then confirm here.</p></div><div className="profile-card"><p className="eyebrow">TARGET PROFILE</p><strong>{preferences.candidateProfile.title}</strong><dl><div><dt>Experience</dt><dd>{preferences.candidateProfile.professionalExperience}</dd></div><div><dt>Preferred range</dt><dd>{preferences.candidateProfile.preferredExperienceRange}</dd></div><div><dt>Locations</dt><dd>{preferences.locations.join(', ')}</dd></div></dl><span className="scan-pill"><i/>{scanStatus.automationStatus||scanStatus.status||'Disabled'}<small>Last success: {scanStatus.lastSuccessfulScan?new Date(scanStatus.lastSuccessfulScan).toLocaleString():'Not yet'}</small></span></div></div><div className="stat-grid dashboard-stats">{stats.map(([label,value,Icon])=><article className="stat-card" key={label}><div><span>{label}</span><strong>{value}</strong></div><Icon/></article>)}</div><div className="daily-goal"><strong>Today: {appliedToday} / {settings.dailyGoal} applied</strong><div><i style={{width:`${Math.min(100,appliedToday/settings.dailyGoal*100)}%`}}/></div><small>The goal tracks manual submissions only.</small></div><div className="dashboard-sections"><section className="panel"><div className="section-head"><div><p className="eyebrow">APPLY QUEUE</p><h3>Recommended to Apply</h3></div><Link to="/jobs">View all <ArrowRight size={15}/></Link></div><MiniList jobs={queue.slice(0,6)} empty="No recent 80%+ unapplied jobs."/></section><section className="panel"><p className="eyebrow">TOP MATCHES</p><h3>Highest CV fit</h3><MiniList jobs={sortJobs(jobs).slice(0,6)}/></section><section className="panel"><p className="eyebrow">RECENT JOBS</p><h3>Newest indexed</h3><MiniList jobs={[...jobs].sort((a,b)=>jobTime(b)-jobTime(a)).slice(0,6)}/></section><section className="panel"><p className="eyebrow">FOLLOW-UPS DUE</p><h3>Manual follow-up reminders</h3><MiniList jobs={followups.slice(0,6)} empty="No follow-ups due."/></section><section className="panel"><p className="eyebrow">RECENT APPLICATIONS</p><h3>Your pipeline</h3><MiniList jobs={[...applications].sort((a,b)=>new Date(b.applicationDate||b.applicationStartedAt)-new Date(a.applicationDate||a.applicationStartedAt)).slice(0,6)} empty="No applications started."/></section></div></>
}
