import { useState } from 'react'
import preferences from '../config/jobPreferences.js'
import { useJobs } from '../context/JobContext'
import { loadApplicationProfile, saveApplicationProfile } from '../services/profileService'

export default function Settings(){
  const {settings,updateSettings}=useJobs(), [profile,setProfile]=useState(loadApplicationProfile)
  const updateProfile=(key,value)=>{const next={...profile,[key]:value};setProfile(next);saveApplicationProfile(next)}
  return <div className="settings-grid"><section className="panel"><p className="eyebrow">CV MATCH PROFILE</p><h3>{profile.professionalTitle}</h3><div className="candidate-summary"><span><small>Professional experience</small><strong>{profile.professionalExperience}</strong></span><span><small>Preferred range</small><strong>{profile.preferredExperienceRange}</strong></span></div>{[['Target roles',preferences.roles],['CV skills',preferences.skills],['Locations',preferences.locations],['Experience priorities',preferences.preferredExperience],['2-year stretch when skills match',preferences.stretchExperience],['Work modes',preferences.workModes],['Excluded/deprioritized',preferences.exclusionKeywords]].map(([label,values])=><div className="preference" key={label}><strong>{label}</strong><div className="tag-row">{values.map(v=><span key={v}>{v}</span>)}</div></div>)}</section><section className="panel simple-form"><p className="eyebrow">BROWSER-LOCAL APPLICATION PROFILE</p><h3>Private profile fields</h3><label>Name<input value={profile.name} onChange={e=>updateProfile('name',e.target.value)}/></label><label>Professional title<input value={profile.professionalTitle} onChange={e=>updateProfile('professionalTitle',e.target.value)}/></label><label>Experience summary<textarea rows="5" value={profile.experienceSummary} onChange={e=>updateProfile('experienceSummary',e.target.value)}/></label><label>Education<textarea rows="3" value={profile.education} onChange={e=>updateProfile('education',e.target.value)} placeholder="Stored only in this browser"/></label><label>Active resume<input value={profile.activeResume} onChange={e=>updateProfile('activeResume',e.target.value)}/></label><p className="fine-print">Email and phone are intentionally not embedded in public source.</p><hr/><p className="eyebrow">AUTOMATION PREFERENCES</p><label className="toggle-row"><span>Automatic in-app alerts<small>New, high-match, remote, follow-up and interview alerts</small></span><input type="checkbox" checked={settings.notifications} onChange={e=>updateSettings({notifications:e.target.checked})}/></label><label>High match threshold<input type="number" min="0" max="100" value={settings.threshold} onChange={e=>updateSettings({threshold:Number(e.target.value)})}/></label><label>Daily application goal<input type="number" min="1" max="50" value={settings.dailyGoal} onChange={e=>updateSettings({dailyGoal:Number(e.target.value)})}/></label><label>Archive jobs older than (days)<input type="number" min="1" max="365" value={settings.archiveDays} onChange={e=>updateSettings({archiveDays:Number(e.target.value)})}/></label><div className="security-box"><strong>No credentials stored</strong><p>API credentials belong only in GitHub repository secrets or a secure backend.</p></div></section></div>
}
