import { createContext,useContext,useEffect,useMemo,useState } from 'react'
import seedJobs from '../data/jobs.json'
import { deduplicateJobs,duplicateKey,normalizeJob,validateJob } from '../services/jobService'
import { storageService } from '../services/storageService'
import { activeResume,resumeLabel } from '../services/resumeService'
import { defaultResume,migrateResumes } from '../config/resumeProfile'
const JobContext=createContext(null);const sanitize=jobs=>deduplicateJobs((Array.isArray(jobs)?jobs:[]).map(normalizeJob).filter(job=>validateJob(job).valid))
export function JobProvider({children}){const[jobs,setJobs]=useState(()=>sanitize(storageService.load('jobs',seedJobs)));const[resumes,setResumes]=useState(()=>migrateResumes(storageService.load('resumes',[defaultResume])));useEffect(()=>storageService.save('jobs',jobs),[jobs]);useEffect(()=>storageService.save('resumes',resumes),[resumes]);const actions=useMemo(()=>({addJob(job){const next=normalizeJob(job),validation=validateJob(next);if(!validation.valid)return{ok:false,message:validation.reason};if(jobs.some(item=>duplicateKey(item)===duplicateKey(next)))return{ok:false,message:'This job is already tracked.'};setJobs(current=>[next,...current]);return{ok:true}},updateJob(id,updates){const current=jobs.find(job=>job.id===id),next=normalizeJob({...current,...updates,id}),validation=validateJob(next);if(!validation.valid)return{ok:false,message:validation.reason};setJobs(items=>items.map(job=>job.id===id?next:job));return{ok:true}},markApplied(id){const resume=activeResume(resumes);setJobs(items=>items.map(job=>job.id===id?normalizeJob({...job,status:'Applied',applicationDate:new Date().toISOString().slice(0,10),resumeVersion:resumeLabel(resume)}):job));return{ok:true}},deleteJob(id){setJobs(current=>current.filter(job=>job.id!==id))}}),[jobs,resumes]);return <JobContext.Provider value={{jobs,resumes,setResumes,...actions}}>{children}</JobContext.Provider>}
export const useJobs=()=>useContext(JobContext)
